<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-2BIDBLH" failures="2" tests="2" name="Test(failed)" time="1.179" errors="0" timestamp="2022-11-17T18:34:34 IST">
  <testcase classname="testNGStudy.FailedTCExecution" name="A" time="1.029">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testNGStudy.FailedTCExecution.A() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testNGStudy.FailedTCExecution.A() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- A -->
  <testcase classname="testNGStudy.FailedTCExecution" name="C" time="0.012">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testNGStudy.FailedTCExecution.C(FailedTCExecution.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- C -->
  <testcase classname="testNGStudy.FailedTCExecution" name="B" time="0.0">
    <ignored/>
  </testcase> <!-- B -->
  <testcase classname="testNGStudy.FailedTCExecution" name="E" time="0.0">
    <ignored/>
  </testcase> <!-- E -->
  <testcase classname="testNGStudy.FailedTCExecution" name="D" time="0.0">
    <ignored/>
  </testcase> <!-- D -->
</testsuite> <!-- Test(failed) -->
